### ISSUE TITLE
При создании объекта, в классе SavingAccount не учтены пределы баланса.

### ISSUE THREAD

**Issue by Anna200592** [Anna200592/UpdateCreditAccount#1]
# Описание
 Сберегательный счёт может иметь баланс только в пределах от указанного минимального до указанного максимального включительно.

# Локация дефекта
https://github.com/Anna200592/UpdateCreditAccount/blob/c989233b91961ab352c09cf338788bb39fd59695/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L24

# Шаги воспроизведения

1. Создать объект тестируемого класса SavingAccount с начальным значениями (начальный баланс 0, минимальный баланс 1_000, максимальный баланс 15_000, процентная ставка 5).
2. Отправить сумму 500 на сберегательный счет, вызовом метода .add(500).

*Ожидаемый результат:* В результате сумма на балансе должна быть = 0, так как баланс ниже минимальных значений.
*Фактический результат:* Баланс пополнился на сумму 500.

# Скриншот
![1](https://github.com/Anna200592/UpdateCreditAccount/assets/125764446/251abc4a-e733-4643-9255-582d61339ede)

# Тест проверки
https://github.com/Anna200592/UpdateCreditAccount/blob/c989233b91961ab352c09cf338788bb39fd59695/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L82-L93

# Окружение
* **Операционная система:** Windows 10.
* **IDEA:** IntelliJ IDEA Community Edition 2023.1
* **Java:** OpenJDK 11

**Comment by tervi888** [comment]
Исправлено
