### ISSUE TITLE
При создании объекта, в классе SavingAccount неверно указаны значения процентной ставки.

### ISSUE THREAD

**Issue by Anna200592** [Anna200592/UpdateCreditAccount#2]
# Описание
Объект сберегательного счёта с параметрами процентной ставки должно быть неотрицательное число.

# Локация дефекта

https://github.com/Anna200592/UpdateCreditAccount/blob/85474012e18e1a9e0cfc05d2274de8c95833f7b8/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L24-L29

# Шаги воспроизведения

1. Создать объект тестируемого класса SavingAccount с начальным значениями (начальный баланс 2_000, минимальный баланс 1_000, максимальный баланс 15_000, процентная ставка 0).

*Ожидаемый результат:* Возможно выставить значение процентной ставки = 0
*Фактический результат:* Вывод сообщения об ошибке "Накопительная ставка не может быть отрицательной, а у вас: 0 ".

# Скриншот
![1](https://github.com/Anna200592/UpdateCreditAccount/assets/125764446/948faad1-7ce0-4d09-b0bb-a3e816512a14)

# Тест проверки
![Screenshot_2](https://github.com/Anna200592/UpdateCreditAccount/assets/125764446/d8a5e8b8-5a80-43e6-b322-4d35e0784c2d)

# Окружение
* **Операционная система:** Windows 10.
* **IDEA:** IntelliJ IDEA Community Edition 2023.1
* **Java:** OpenJDK 11

**Comment by tervi888** [comment]
Исправленно
